### ISSUE TITLE
Can't run tests or build or bootstrap due to errors: "Invalid Tool field" or "Unknown blueprint"

### ISSUE THREAD

**Issue by kaiyoma** [williaster/data-ui#207]
I followed the instructions in the readme (clone, install, bootstrap), but even after that, none of the package commands work. They all fail with the same "invalid tool" error:

```
$ npm run test

> @data-ui/histogram@0.0.84-arista test C:\Work\data-ui\packages\histogram
> yarn run jest

yarn run v1.22.5
$ beemo jest --react --color --coverage
C:\Work\data-ui\packages\histogram\node_modules\optimal\lib\index.js:198
        throw new Error(prefix + ". " + error);
        ^

Error: Invalid Tool field "configName". Config file name must be camel case without extension.
    at StringPredicate.invariant (C:\Work\data-ui\packages\histogram\node_modules\optimal\lib\index.js:198:15)
    at StringPredicate.<anonymous> (C:\Work\data-ui\packages\histogram\node_modules\optimal\lib\index.js:137:18)
    at C:\Work\data-ui\packages\histogram\node_modules\optimal\lib\index.js:333:28
    at Array.forEach (<anonymous>)
    at StringPredicate.validate (C:\Work\data-ui\packages\histogram\node_modules\optimal\lib\index.js:332:17)
    at StringPredicate.run (C:\Work\data-ui\packages\histogram\node_modules\optimal\lib\index.js:315:23)
    at C:\Work\data-ui\packages\histogram\node_modules\optimal\lib\index.js:520:39
    at Array.forEach (<anonymous>)
    at Schema.build (C:\Work\data-ui\packages\histogram\node_modules\optimal\lib\index.js:511:33)
    at Object.optimal [as default] (C:\Work\data-ui\packages\histogram\node_modules\optimal\lib\index.js:575:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @data-ui/histogram@0.0.84-arista test: `yarn run jest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @data-ui/histogram@0.0.84-arista test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by kaiyoma** [comment]
The above output occurred on my Windows 10 laptop. I tried the same steps on a Linux box and got different errors while trying to bootstrap (which are similar to other issues I've seen):

```
> npm run bootstrap

> @data-ui/data-ui@0.0.0 bootstrap .../data-ui
> lerna bootstrap

lerna notice cli v3.22.1
lerna notice filter excluding "build-config"
lerna info filter [ '!build-config' ]
lerna info Bootstrapping 11 packages
lerna info Installing external dependencies
lerna info Symlinking packages and binaries
lerna info lifecycle @data-ui/data-table@0.0.84~prepublish: @data-ui/data-table@0.0.84
lerna info lifecycle @data-ui/theme@0.0.84~prepublish: @data-ui/theme@0.0.84
lerna info lifecycle @data-ui/forms@0.0.84~prepublish: @data-ui/forms@0.0.84

> @data-ui/data-table@0.0.84 prepublish .../data-ui/packages/data-table
> yarn run build

yarn run v1.22.10
$ yarn run build:cjs && yarn run build:esm
$ beemo babel ./src --out-dir lib/ --react --minify

Unknown blueprint for "configure". Must be a predicate.
    at .../data-ui/packages/data-table/node_modules/optimal/lib/index.js:522:15
    at Array.forEach (<anonymous>)
    at Schema.build (.../data-ui/packages/data-table/node_modules/optimal/lib/index.js:511:33)
    at Object.optimal [as default] (.../data-ui/packages/data-table/node_modules/optimal/lib/index.js:575:17)
    at ConfigLoader.loadConfig (.../data-ui/packages/data-table/node_modules/@boost/core/lib/ConfigLoader.js:202:41)
    at Tool.loadConfig (.../data-ui/packages/data-table/node_modules/@boost/core/lib/Tool.js:394:41)
    at Tool.initialize (.../data-ui/packages/data-table/node_modules/@boost/core/lib/Tool.js:289:14)
    at new Beemo (.../data-ui/packages/data-table/node_modules/@beemo/core/lib/Beemo.js:42:14)
    at Object.<anonymous> (.../data-ui/packages/data-table/node_modules/@beemo/cli/lib/CLI.js:17:15)
    at Module._compile (internal/modules/cjs/loader.js:776:30)

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna info lifecycle @data-ui/data-table@0.0.84~prepublish: Failed to exec prepublish script

> @data-ui/theme@0.0.84 prepublish .../data-ui/packages/data-ui-theme
> yarn run build

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @data-ui/data-ui@0.0.0 bootstrap: `lerna bootstrap`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @data-ui/data-ui@0.0.0 bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     .../.npm/_logs/2020-12-01T05_04_50_003Z-debug.log
yarn run v1.22.10
$ yarn run build:cjs && yarn run build:esm
$ beemo babel ./src --out-dir lib/ --minify

Unknown blueprint for "configure". Must be a predicate.
    at .../data-ui/packages/data-ui-theme/node_modules/optimal/lib/index.js:522:15
    at Array.forEach (<anonymous>)
    at Schema.build (.../data-ui/packages/data-ui-theme/node_modules/optimal/lib/index.js:511:33)
    at Object.optimal [as default] (.../data-ui/packages/data-ui-theme/node_modules/optimal/lib/index.js:575:17)
    at ConfigLoader.loadConfig (.../data-ui/packages/data-ui-theme/node_modules/@boost/core/lib/ConfigLoader.js:202:41)
    at Tool.loadConfig (.../data-ui/packages/data-ui-theme/node_modules/@boost/core/lib/Tool.js:394:41)
    at Tool.initialize (.../data-ui/packages/data-ui-theme/node_modules/@boost/core/lib/Tool.js:289:14)
    at new Beemo (.../data-ui/packages/data-ui-theme/node_modules/@beemo/core/lib/Beemo.js:42:14)
    at Object.<anonymous> (.../data-ui/packages/data-ui-theme/node_modules/@beemo/cli/lib/CLI.js:17:15)
    at Module._compile (internal/modules/cjs/loader.js:776:30)

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by williaster** [comment]
Hi, this repo is no longer maintained, please see #201

**Comment by kaiyoma** [comment]
> Hi, this repo is no longer maintained, please see #201

Yes, I realize that, but I'm looking for some guidance on how to get this build working. I'm trying to make my own fork that fixes some issues, but there seem to be some fundamental build issues precluding that.

**Comment by williaster** [comment]
Sorry, the build system is quite old and unfortunately there is a non-trivial amount of work needed to get it working again.
